using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// ScriptableObject container for ALL visual asset references (sprites,
/// materials, colors) used by the game. Real assets can be dropped into the
/// inspector later without touching game logic.
///
/// In Phase A, every field is optional: when an override is null, the theme
/// falls back to a programmatic sprite generated by SpriteGenerator (cached
/// per color/type) so the game runs with zero imported art.
/// </summary>
[CreateAssetMenu(fileName = "VisualTheme", menuName = "HappyMatch/VisualTheme", order = 1)]
public class VisualTheme : ScriptableObject
{
    [Header("Element Colors (used for procedural fallback)")]
    public Color colorRed = new Color(0.9f, 0.2f, 0.2f);
    public Color colorBlue = new Color(0.2f, 0.4f, 0.9f);
    public Color colorYellow = new Color(0.95f, 0.85f, 0.2f);
    public Color colorGreen = new Color(0.2f, 0.8f, 0.3f);
    public Color colorSuitcase = new Color(0.9f, 0.6f, 0.1f);

    [Header("Board / Background")]
    public Color boardCellColor = new Color(1f, 1f, 1f, 0.08f);
    public Color backgroundColor = new Color(0.102f, 0.102f, 0.18f, 1f);

    [Header("Optional Sprite Overrides (leave null for procedural)")]
    public Sprite spriteRed;
    public Sprite spriteBlue;
    public Sprite spriteYellow;
    public Sprite spriteGreen;
    public Sprite spriteSuitcase;

    [Header("Optional Special Sprite Overrides (leave null for procedural)")]
    public Sprite spriteRocket;
    public Sprite spriteBomb;
    public Sprite spritePropeller;

    private readonly Dictionary<Color, Sprite> _circleCache = new Dictionary<Color, Sprite>();
    private Sprite _suitcaseCache;
    private readonly Dictionary<Color, Sprite> _rocketCache = new Dictionary<Color, Sprite>();
    private readonly Dictionary<Color, Sprite> _bombCache = new Dictionary<Color, Sprite>();
    private readonly Dictionary<Color, Sprite> _propellerCache = new Dictionary<Color, Sprite>();
    // Phase E: distinct outline per element (stocking/snowflake/star/tree), cached
    // per type so repeated requests don't regenerate the texture.
    private Sprite _redShape, _blueShape, _yellowShape, _greenShape;

    private static VisualTheme _default;

    public static VisualTheme Default
    {
        get
        {
            if (_default == null)
                _default = CreateInstance<VisualTheme>();
            return _default;
        }
    }

    public Color GetColorForType(ElementType type)
    {
        switch (type)
        {
            case ElementType.Red: return colorRed;
            case ElementType.Blue: return colorBlue;
            case ElementType.Yellow: return colorYellow;
            case ElementType.Green: return colorGreen;
            case ElementType.Suitcase: return colorSuitcase;
            default: return Color.white;
        }
    }

    /// <summary>
    /// Resolve the sprite for a normal element or suitcase, using an override
    /// if provided, otherwise a cached procedural sprite. Phase E gives each
    /// normal element a distinct outline (hat/snowflake/star/tree).
    /// </summary>
    public Sprite GetElementSprite(ElementType type)
    {
        switch (type)
        {
            case ElementType.Red:
                return spriteRed ?? (_redShape ?? (_redShape = SpriteGenerator.CreateStockingSprite(colorRed)));
            case ElementType.Blue:
                return spriteBlue ?? (_blueShape ?? (_blueShape = SpriteGenerator.CreateSnowflakeSprite(colorBlue)));
            case ElementType.Yellow:
                return spriteYellow ?? (_yellowShape ?? (_yellowShape = SpriteGenerator.CreateStarSprite(colorYellow)));
            case ElementType.Green:
                return spriteGreen ?? (_greenShape ?? (_greenShape = SpriteGenerator.CreateTreeSprite(colorGreen)));
            case ElementType.Suitcase:
                return spriteSuitcase ?? (_suitcaseCache ?? (_suitcaseCache = SpriteGenerator.CreateSuitcaseSprite(colorSuitcase)));
            default:
                return GetCachedCircle(Color.white);
        }
    }

    public Sprite GetRocketSprite(ElementType type)
    {
        if (spriteRocket != null) return spriteRocket;
        Color c = GetColorForType(type);
        if (!_rocketCache.ContainsKey(c))
            _rocketCache[c] = SpriteGenerator.CreateRocketSprite(c);
        return _rocketCache[c];
    }

    public Sprite GetBombSprite(ElementType type)
    {
        if (spriteBomb != null) return spriteBomb;
        Color c = GetColorForType(type);
        if (!_bombCache.ContainsKey(c))
            _bombCache[c] = SpriteGenerator.CreateBombSprite(c);
        return _bombCache[c];
    }

    public Sprite GetPropellerSprite(ElementType type)
    {
        if (spritePropeller != null) return spritePropeller;
        Color c = GetColorForType(type);
        if (!_propellerCache.ContainsKey(c))
            _propellerCache[c] = SpriteGenerator.CreatePropellerSprite(c);
        return _propellerCache[c];
    }

    /// <summary>
    /// Convenience: resolve a sprite for a cell given its type + special.
    /// Mirrors the old GameManager.GetSpriteForType signature so callers can
    /// route through the theme without changing their API.
    /// </summary>
    public Sprite GetSpriteForType(ElementType type, GameConfig.SpecialType special = GameConfig.SpecialType.None, GameConfig.RocketDir rocketDir = GameConfig.RocketDir.Horizontal)
    {
        if (special == GameConfig.SpecialType.Rocket) return GetRocketSprite(type);
        if (special == GameConfig.SpecialType.Bomb) return GetBombSprite(type);
        if (special == GameConfig.SpecialType.Propeller) return GetPropellerSprite(type);
        return GetElementSprite(type);
    }

    private Sprite GetCachedCircle(Color c)
    {
        if (!_circleCache.ContainsKey(c))
            _circleCache[c] = SpriteGenerator.CreateCircleSprite(c);
        return _circleCache[c];
    }
}
